Repository konidev20/pyshamir, pull requests merged in 2022-11, with the labels that each got.

#6 Packaging changes
  pyshamir/__init__.py
  setup.cfg
  setup.py
Labels: enhancement

#8 Add GitHub workflow to create releases
  .github/workflows/pypi-publish.yml
Labels: enhancement

#15 docs: add lang to codeblocks
  README.md
Labels: documentation

#17 build: add missing asset_name for release
  .github/workflows/pypi-publish.yml
Labels: bug

#18 build: fix version on workflow env
  .github/workflows/pypi-publish.yml
Labels: bug
